# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(0, 'History'), (1, 'Novel'), (2, 'Physics')], max_length=1)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['-id'],
            },
        ),
    ]
